  version: '3'
  networks:
    my-dapr-network:
      external: true
  services:
    ############################
    # serviceone + Dapr sidecar
    ############################
    servicea:
      build: ./serviceA
      ports:
        - "3501:3501"
      expose:
        - 3501
      depends_on:
        - zipkin
        - redis
        - placement
      networks:
        - my-dapr-network

        ############################
        # serviceone Dapr sidecar
        ############################

    servicea-dapr:
      image: "daprio/daprd:edge"
      command: ["./daprd",
                "-app-id", "servicea",
                "--dapr-http-port", "3501",
                "-app-port", "8090",
                "-placement-host-address", "placement:50006",
                "--components-path", "./components",
                "--config","/components/config.yaml",
                "-dapr-grpc-port", "50002"]

      volumes:
        - "./components/:/components"
      depends_on:
        - servicea
      network_mode: "service:servicea"
    
    
    ############################
    # servicetwo + Dapr sidecar
    ############################
    
    serviceb:
      build: ./ServiceB
      ports:
        - "3500:3500"
      
      expose:
        - 3500
      depends_on:
        - zipkin
        - redis
        - placement
      networks:
        - my-dapr-network
      
      
        #####################
        # servicetwo Dapr sidecar
        ############################

    serviceb-dapr:
      image: "daprio/daprd:edge"
      command: ["./daprd",
                "-app-id", "serviceb",
                "--dapr-http-port", "3500",
                "-app-port", "8080",
                "-placement-host-address", "placement:50006",
                "--components-path", "./components",
                "--config","/components/config.yaml",
                "-dapr-grpc-port", "50002"]

      volumes:
        - "./components/:/components"
      depends_on:
        - serviceb
      network_mode: "service:serviceb"

    ############################
    # Dapr placement service
    ############################
    placement:
      image: "daprio/dapr"
      command: ["./placement", "-port", "50006"]
      ports:
        - "50006:50006"
      networks:
        - my-dapr-network
    ############################
    # Redis state store
    ############################
    redis:
      image: "redis"
      ports:
        - "6379:6379"
      expose:
        - 6379
      networks:
        - my-dapr-network

    ############################
    # Zipkin
    ############################
    zipkin:
      image: "openzipkin/zipkin"
      ports:
        - "9411:9411"
      expose:
        - 9411
      networks:
        - my-dapr-network
  
